# frozen_string_literal: true

ruby '3.0.5'
source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'aws-sdk-dynamodb'
gem 'aws-sdk-s3'
gem 'mysql2', '= 0.5.3'
gem 'ox'
gem 'puma'
gem 'rack'
gem 'rack-parser'
gem 'rackup'
gem 'sinatra'
