# frozen_string_literal: true
ruby "3.0.2"
source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "rack"
gem "rackup"
gem "rack-parser"
gem "puma"
gem "sinatra"
gem "aws-sdk-dynamodb"
gem "ox"
